
modLoader = "javafml"
loaderVersion = "[36,)"
license = "All Rights Reserved"
[[mods]]
modId = "gribcore"
version = "${version}"
displayName = "GribCore"
authors = "AlgorithmLX"
description = '''
this is description
'''
[[dependencies.gribcore]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.gribcore]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"
#[[dependencies.gribcore]]
#modId = "minecraft"
#mandatory = true
## This version range declares a minimum of the current minecraft version up to but not including the next major version
#versionRange = "[*)"
#ordering = "NONE"
#side = "BOTH"
